### NumPy: Функции & Модули [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Пожалуйста, протестируйте все функции, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [2]:
import numpy as np

In [4]:
# numpy.zeros
arr1 = np.zeros((3,2))
print(arr1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
# numpy.ones
arr1 = np.ones((3,2))
print(arr1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# numpy.full
arr1 = np.zeros((3,2))
print(arr1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [35]:
# numpy.eye
arr1 = np.full((3,2),5)
print(arr1)

[[5 5]
 [5 5]
 [5 5]]


In [37]:
# numpy.arange
arr1 = np.arange(40)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [38]:
# numpy.add
arr1 = np.add((3,2),4)
print(arr1)

[7 6]


In [40]:
# numpy.subtract
arr1 = np.subtract((3,2),7)
print(arr1)

[-4 -5]


In [12]:
# numpy.sin
arr1 = np.sin((3,2))
print(arr1)

[0.14112001 0.90929743]


In [13]:
# numpy.multiply
arr1 = np.zeros((3,2))
print(arr1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [41]:
# numpy.sqrt
arr1 = np.multiply((3,2),90)
print(arr1)

[270 180]


In [43]:
# numpy.dot
arr1 = np.dot((3,2),90)
print(arr1)

[270 180]


In [16]:
# numpy.sum
arr1 = np.sum((3,2))
print(arr1)

5


In [17]:
# numpy.zeros_like
arr1 = np.zeros_like((3,2))
print(arr1)

[0 0]


In [18]:
# numpy.empty_like
arr1 = np.empty_like((3,2))
print(arr1)

[105647520       643]


In [51]:
# numpy.reshape
a = np.array([1,4,5,56,6,7,8,9])
arr1 = a.reshape((2,4))
print(arr1)

[[ 1  4  5 56]
 [ 6  7  8  9]]


In [20]:
# numpy.isnan
arr1 = np.isnan((3,2))
print(arr1)

[False False]


2. Пожалуйста, протестируйте все функции модуля ```numpy.random```, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [21]:
import numpy.random as rd

In [23]:
# numpy.random.sample
rd.sample((3,4))

array([[6.77474707e-01, 2.66958596e-01, 1.32239448e-01, 3.67497840e-01],
       [1.64495797e-01, 1.18300031e-01, 5.73893888e-02, 7.55754764e-01],
       [9.86150999e-01, 9.10729488e-05, 4.40608841e-01, 1.75905630e-03]])

In [24]:
# numpy.random.random
rd.random((3,4))

array([[5.62958639e-02, 4.91975075e-01, 8.71312870e-01, 6.75976209e-04],
       [3.70664673e-01, 8.11051964e-01, 1.11009242e-01, 7.32285412e-01],
       [2.17475579e-01, 4.20827235e-01, 5.51960213e-01, 4.95348161e-01]])

In [66]:
# numpy.random.randint
rd.randint((1,4))

array([0, 2])

In [67]:
# numpy.random.random_integers
rd.random_integers(1,4,(3,4))

C:\Users\User\.conda\envs\py36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 4 + 1) instead
  


array([[3, 4, 2, 2],
       [1, 1, 4, 4],
       [1, 4, 1, 1]])

In [71]:
# numpy.random.uniform
rd.uniform((3,4))

array([2.81377844, 1.26867344])

In [77]:
# numpy.random.seed
rd.seed(0)
a = rd.randint(10, size=6)
a

array([5, 0, 3, 3, 7, 9])

In [78]:
# numpy.random.shuffle
arr1  =np.arange(6)
rd.shuffle((arr1))
print(arr1)

[1 5 4 0 2 3]


In [82]:
# numpy.random.permutation
data = rd.permutation([1,2,3,5,8,9])
data

array([5, 9, 2, 3, 8, 1])

In [85]:
# numpy.random.choice
rd.choice((10000,9999))

9999

# Прекрасная работа!