### NumPy: Индексы & Срезы [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [36]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.19.5


### Ожидаемый результат
```
1.17.4
```

2. Вам предоставляется список ```list1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]```.
Пожалуйста, извлеките элементы списка ```list1```, который разделяет его индекс в списке ```list1``` без остатка. Используйте два подхода для решения этой проблемы, используя только список ```list``` и используя массив ```numpy.ndarray``` отдельно.

    **Примечание: не используйте ```enumerate```.**

In [5]:
list_1[2]

5

In [16]:
list_1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]
list_2 = []
a = []
b = []

for i in range(len(list_1)):
    a.append(i)

for j in list_1:
    b.append(j)
  
for num1,num2 in zip(a,b):
    if num1%num2==0:
        list_2.append(num2)
print(list_2)
# Конец вашего кода


[1, 5, 2]


In [10]:
list_1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]
list_2 = []

for i in range(len(list_1)):
    if i%list_1[i]==0:
        list_2.append(list_1[i])
    
    
print(list_2)

[1, 5, 2]


In [38]:
list_1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]

arr = np.array([1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423])
idx = np.arange(len(arr))
div = idx/arr
 
print(arr[div == div.astype(int)]) 

[1 5 2]


### Ожидаемый результат
```
[1, 5, 2]
```

### Ожидаемый результат
```
[1 5 2]
```

3. Вам предоставляется список списков ```list_of_lists=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]```. Пожалуйста, извлеките элементы, которые делят произведение индекса строки и индекса столбца без остатка.Используйте два подхода для решения этой проблемы, используя только список list и используя массив numpy.ndarray отдельно.

**Примечание: не используйте ```enumerate```.**

In [44]:
list_of_lists = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]]
list_2 = []
for i in range(len(list_of_lists)):
    
    for j in range(len(list_of_lists[i])):
        
        if  i*j %list_of_lists[i][j]==0:
            list_2.append(list_of_lists[i][j])
            
            #list_2.append(list_of_lists[i])
    
            
        
print(list_2)        
    


[1, 2, 3, 4, 5, 9]


### Ожидаемый результат
```
[1, 2, 3, 4, 5, 9]
```

In [48]:
# numpy.ndarray
# Начало вашего кода
arr = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

list_2 = []
for i in range(len(arr)):
    
    for j in range(len(arr[i])):
        
        if  i*j %arr[i,j]==0:
            list_2.append(arr[i,j])
            ndarr = np.array(list_2)

# Конец вашего кода

print(ndarr)


[1 2 3 4 5 9]


### Ожидаемый результат
```
[1 2 3 4 5 9]
```

4. Пожалуйста, напишите две функции:

```slice_list(orig_list, row_str, row_end, col_str, col_end)```

```slice_list_ndarr(orig_list, row_str, row_end, col_str, col_end)```


row_str и row_end - начальный индекс столбца и конечный индекс столбца среза.

col_str и col_end - начальный индекс столбца и конечный индекс столбца среза.

Пример:
```
orig_list =[[ 1, 2, 3],
            [11,12,13],
            [21,22,23]]

res_list = slice_list(orig_list, 0, 2, 1, 3)

Ответ:
res_list = [[ 2, 3],
            [12,13]]

```

In [126]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

def slice_list(orig_list, row_str, row_end, col_str, col_end):
    # list
    # Начало вашего кода
    answer = []
    
    for i in range(row_str, row_end):
        row = []
        for j in range(col_str, col_end):
            row.append(orig_list[i][j])
        
        answer.append(row)
            
    return answer 
    # Конец вашего кода

print(slice_list(list_of_lists,1,4,1,3))


[[6, 7], [10, 11], [14, 15]]


### Ожидаемый результат
```
[[6, 7], [10, 11], [14, 15]]
```

In [20]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

def slice_list_ndarr(orig_list, row_str, row_end, col_str, col_end):
    # numpy.ndarray
    # Начало вашего кода
    a=np.array(orig_list)
    b=a[row_str:row_end, col_str:col_end]
    return b.tolist()
    
    # Конец вашего кода

print(slice_list_ndarr(list_of_lists,1,4,1,3))

[[6, 7], [10, 11], [14, 15]]


### Ожидаемый результат
```
[[6, 7], [10, 11], [14, 15]]
```

# Прекрасная работа!