### NumPy: Введение (Часть 2) [Домашнее задание]

> **Пожалуйста, избегайте использования одномерных массивов numpy.ndarray.**
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [2]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.19.5


### Ожидаемый результат
```
1.17.4
```

2. Создайте двумерный numpy.ndarray **numbers**, где первая строка содержит четные числа от 0 до 10, а вторая строка содержит нечетные числа от 0 до 10 (10 не учитывается в обоих случаях).

In [3]:
# Начало вашего кода
even = []
odd = []
numbers = []
for i in range(0,10):
    if i%2==0:
        even.append(i)
    else:
        odd.append(i)
numbers = [even,odd]
numbers_np = np.array(numbers)
# Конец вашего кода
print(numbers_np)

[[0 2 4 6 8]
 [1 3 5 7 9]]


### Ожидаемый результат
```
[[0 2 4 6 8]
 [1 3 5 7 9]]
```

3. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [4]:
# Начало вашего кода
print(numbers_np.ndim)
print(numbers_np.shape)
print(numbers_np.size)
print(numbers_np.dtype)

numbers_np_2 = numbers_np.transpose()
print(numbers_np_2)
# Конец вашего кода

2
(2, 5)
10
int32
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Ожидаемый результат
```
2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

4. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray.

In [5]:
# Начало вашего кода
overall_max = numbers_np.max()
overall_min = numbers_np.min()
overall_mean = numbers_np.mean()
overall_std = numbers_np.std()

# Конец вашего кода
print(overall_max)
print(overall_min)
print(overall_mean)
print(overall_std)

9
0
4.5
2.8722813232690143


### Ожидаемый результат
```
9
0
4.5
2.8722813232690143
```

5. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждого **столбца**.

In [6]:
print(numbers_np_2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
# Начало вашего кода
col_max = numbers_np_2.max(axis=1) 

col_min = numbers_np_2.min(axis=1) 
    
col_mean = numbers_np_2.mean(axis=1) 

col_std = numbers_np_2.std(axis=1) 
    
# Конец вашего кода
print(col_max)
print(col_min)
print(col_mean)
print(col_std)

[1 3 5 7 9]
[0 2 4 6 8]
[0.5 2.5 4.5 6.5 8.5]
[0.5 0.5 0.5 0.5 0.5]


### Ожидаемый результат
```
[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]
```

6. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждой **строки**.

In [17]:
# Начало вашего кода

row_max = np.max(numbers_np, axis = 1, keepdims=True)

    
row_min = np.min(numbers_np, axis = 1, keepdims=True)


row_mean = np.mean(numbers_np, axis = 1, keepdims=True)

row_std = np.std(numbers_np, axis = 1, keepdims=True)
# Конец вашего кода
print(row_max)
print(row_min)
print(row_mean)
print(row_std)

[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]


### Ожидаемый результат
```
[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]
```

7. Создайте объект numpy.ndarray из списка list_of_lists, приведенного ниже. Кроме того, рассчитать среднее значение и стандартное отклонение по всем осям.

In [19]:
list_of_lists = [[[1,2],[3,4]],[[21,22],[23,24]]]
# Начало вашего кода
thd_nparr = np.array(list_of_lists)
# Конец вашего кода
print(thd_nparr)

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


### Ожидаемый результат
```
[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]
```

In [21]:
# Начало вашего кода
result_1 = thd_nparr.mean(axis=0)
print('Mean with respect to 0-axis')
print(result_1)

result_1 = thd_nparr.std(axis=0)
print('STD with respect to 0-axis')
print(result_1)



result_2 = thd_nparr.mean(axis=1)
print('Mean with respect to 1-axis')
print(result_2)

result_2 = thd_nparr.std(axis=1)
print('STD with respect to 1-axis')
print(result_2)




result_3 = thd_nparr.mean(axis=2, keepdims=True)
print('Mean with respect to 2-axis')
print(result_3)

result_3 = thd_nparr.std(axis=2, keepdims=True)
print('STD with respect to 2-axis')
print(result_3)



Mean with respect to 0-axis
[[11. 12.]
 [13. 14.]]
STD with respect to 0-axis
[[10. 10.]
 [10. 10.]]
Mean with respect to 1-axis
[[ 2.  3.]
 [22. 23.]]
STD with respect to 1-axis
[[1. 1.]
 [1. 1.]]
Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]


### Ожидаемый результат
```
Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]


Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]


Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]
```

8. Пожалуйста, предоставьте применение следующих методов numpy.ndarray ниже:

In [12]:
# ndarray.reshape()
# Начало вашего кода
thd_nparr_2 = thd_nparr.transpose()
print(thd_nparr_2)
# Конец вашего кода

[[[ 1 21]
  [ 3 23]]

 [[ 2 22]
  [ 4 24]]]


In [13]:
# ndarray.ravel()
# Начало вашего кода
thd_nparr_2 = thd_nparr.ravel()
print(thd_nparr_2)
# Конец вашего кода

[ 1  2  3  4 21 22 23 24]


In [17]:
# ndarray.tolist()
# Начало вашего кода
thd_nparr_2 = thd_nparr.tolist()
print(thd_nparr_2)
# Конец вашего кода

[[[1, 2], [3, 4]], [[21, 22], [23, 24]]]


In [40]:
# ndarray.tofile()
# Начало вашего кода
thd_nparr.tofile('thd_nparr.bin')
a = np.fromfile('thd_nparr.bin', dtype=np.float)
a
# Конец вашего кода

array([4.24399158e-314, 8.48798317e-314, 4.66839074e-313, 5.09278990e-313])

In [44]:
# ndarray.sort()
# Начало вашего кода
a = np.array(thd_nparr)
a.sort(axis=1)
a

# Конец вашего кода

array([[[ 1,  2],
        [ 3,  4]],

       [[21, 22],
        [23, 24]]])

In [26]:
# ndarray.transpose()
# Начало вашего кода
thd_nparr_2 = thd_nparr.transpose()
print(thd_nparr_2)
# Конец вашего кода

[[[ 1 21]
  [ 3 23]]

 [[ 2 22]
  [ 4 24]]]


In [27]:
# ndarray.flatten()
# Начало вашего кода
thd_nparr_2 = thd_nparr.flatten()
print(thd_nparr_2)
# Конец вашего кода

[ 1  2  3  4 21 22 23 24]


In [28]:
# ndarray.argmin()
# Начало вашего кода
thd_nparr_2 = thd_nparr.argmin()
print(thd_nparr_2)
# Конец вашего кода

0


In [29]:
# ndarray.argmax()
# Начало вашего кода
thd_nparr_2 = thd_nparr.argmax()
print(thd_nparr_2)
# Конец вашего кода

7


In [30]:
# ndarray.cumsum()
# Начало вашего кода
thd_nparr_2 = thd_nparr.cumsum()
print(thd_nparr_2)
# Конец вашего кода

[  1   3   6  10  31  53  76 100]


In [31]:
# ndarray.cumprod()
# Начало вашего кода
thd_nparr_2 = thd_nparr.cumprod()
print(thd_nparr_2)
# Конец вашего кода

[      1       2       6      24     504   11088  255024 6120576]


In [56]:
# ndarray.dot()
# Начало вашего кода
np.dot([1,2,3],[2,5,6])

# Конец вашего кода

30

In [33]:
# ndarray.squeeze()
# Начало вашего кода
thd_nparr_2 = thd_nparr.squeeze()
print(thd_nparr_2)
# Конец вашего кода

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


In [60]:
# ndarray.repeat()
# Начало вашего кода
x = np.array([thd_nparr])
np.repeat(x, 2)
# Конец вашего кода

array([ 1,  1,  2,  2,  3,  3,  4,  4, 21, 21, 22, 22, 23, 23, 24, 24])

# Прекрасная работа!